### ISSUE TITLE
jython: version bump

### ISSUE THREAD

**Issue by johnjiabinzhang** [RuiChen08/dacapobench#17]
Bump the `jython` benchmark to lastest version (2.7.0).

**Comment by johnjiabinzhang** [comment]
The official Jython repo has moved to [Python repo](http://hg.python.org/jython) (mirrored at [BitBucket](https://bitbucket.org/jython/jython).

This requires not only a change of URL, but also adding the support for mercurial (`hg`) version control system.

**Comment by RuiChen08** [comment]
Finished
