### ISSUE TITLE
batik: deprecated package

### ISSUE THREAD

**Issue by johnjiabinzhang** [RuiChen08/dacapobench#2]
The `batik` benchmark uses `com.sun.image.codec.jpeg.*` package. This package is [removed since JDK7 ](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6527962).

A brief check of `batik` benchmark suite [web repo](http://archive.apache.org/dist/xmlgraphics/batik/), the included `v1.7` is still the up-to-date version of the benchmark. Thus a version bump won't be able to fix the issue.

How should we deal with this case?

**Comment by johnjiabinzhang** [comment]
Steve outlined two fixes:
- "fork" the benchmark to be `batik-jdk7`
- find the package and add to the dependency/download for the suite

**Comment by RuiChen08** [comment]
newest version is 1.9
